# Generated by Django 5.1.7 on 2025-04-12 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
