# Generated by Django 5.1.7 on 2025-04-13 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_book_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='favourite',
        ),
    ]
